<a href="https://colab.research.google.com/github/tapodeb/data_science/blob/main/PyTorch_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Sun Jun 11 22:32:01 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print (torch.__version__)

2.0.1+cu118


In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
#check the dimensions of a tensor using the ndim attribute
scalar.ndim

0

In [5]:
#retrieve the number from the tensor OR turn it from torch.Tensor to a Python integer
scalar.item()

7

In [6]:
#vector
vector = torch.tensor([2,3])
vector

tensor([2, 3])

In [7]:
# Check the number of dimensions of vector
vector.ndim

1

In [8]:
#shape defines how the tensor elements are arranged
vector.shape

torch.Size([2])

In [9]:
#Matrix
MATRIX = torch.tensor([[1,2,3],[4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 3])

In [12]:
#index
MATRIX[0]

tensor([1, 2, 3])

In [13]:
#check the tensor dimensions by changing the number of [] brackets
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [6,7,9]]])
print (TENSOR)
TENSOR.shape

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 9]]])


torch.Size([1, 3, 3])

In [14]:
#random tensor
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0366, 0.4470, 0.8253, 0.0437],
        [0.8050, 0.5985, 0.3714, 0.5673],
        [0.1297, 0.6979, 0.0885, 0.8266]])

In [15]:
#tensor of zeros
zeros = torch.zeros(2,5)
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [16]:
#tensor of ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
#identity matrix
I_s = torch.eye(3,5)
I_s

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [18]:
#reset values
random_tensor = torch.rand(3, 4)
print (random_tensor)
zeros = torch.zeros(1)
print(zeros)
random_tensor*zeros

tensor([[5.2665e-01, 2.7223e-01, 4.6616e-01, 5.4210e-01],
        [7.5376e-04, 9.3023e-01, 2.3628e-01, 6.3320e-02],
        [5.8129e-01, 4.5462e-01, 3.8086e-01, 9.3368e-01]])
tensor([0.])


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
#Range
torch.range(1,10)

<ipython-input-19-3785c09540d6>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
#As torch.range might get removed in future - check previous warning, use this
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#craeting tensor of same shape
one_to_ten = torch.arange(start=1, end =11, step=1)
print(one_to_ten)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## **Data Type**
https://pytorch.org/docs/stable/tensors.html

In [22]:
#tensor datatype and attributes
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device


(torch.Size([3]), torch.float32, device(type='cpu'))

In [23]:
# torch.half: half precion than default float32
float_16_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float16) #dtype=torch.half also work
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [24]:
# torch.double: double precion than default float32
float_64_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float64) #dtype=torch.double also work
float_64_tensor, float_64_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float64), torch.float64)

In [25]:
#results to the higher precision data type in a calculation 
tensor_mult_1 = float_32_tensor*float_16_tensor
tensor_mult_2 = float_32_tensor*float_64_tensor
tensor_mult_1.dtype, tensor_mult_2.dtype

(torch.float32, torch.float64)

In [26]:
tensor_add_1 = float_32_tensor+float_16_tensor
tensor_add_2 = float_32_tensor+float_64_tensor
tensor_add_1.dtype, tensor_add_2.dtype

(torch.float32, torch.float64)

## **Math Operations**
Site: https://www.mathsisfun.com/algebra/matrix-multiplying.html

Calculator: https://www.mathsisfun.com/algebra/matrix-calculator.html

Another visual calculator: http://matrixmultiplication.xyz/

In [27]:
# basic math operation
tensor = torch.tensor([1,2,3])
tensor * 10, tensor + 10, tensor - 10, tensor / 10, tensor / 0

(tensor([10, 20, 30]),
 tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([0.1000, 0.2000, 0.3000]),
 tensor([inf, inf, inf]))

In [28]:
# matrix multiplication and dot product
print(f"element-wise multiplication: {tensor} * {tensor} = {tensor * tensor}")
print(f"dot product: torch.matmul(tensor, tensor) = {torch.matmul(tensor, tensor)}")

element-wise multiplication: tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])
dot product: torch.matmul(tensor, tensor) = 14


In [29]:
# In math matrix dot operation is represted as (1,2,3).(1,2,3)
# Above will be solved as 
1*1 + 2*2 + 3*3 

14

In [30]:
# above math can be performed in a python for loop, 
# it gets more complex as the matrix shape increases
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]+tensor[i]
print(value)

tensor(12)
CPU times: user 1.25 ms, sys: 45 µs, total: 1.29 ms
Wall time: 2.11 ms


In [31]:
#using torch is much faster, simple code
%%time
torch.matmul(tensor, tensor)

CPU times: user 62 µs, sys: 11 µs, total: 73 µs
Wall time: 77 µs


tensor(14)

In [32]:
#Tensor aggregation: min, max, mean, sum
x = torch.arange(0,10,1)
x, x.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

In [33]:
# Find minimum
torch.min(x), x.min()

(tensor(0), tensor(0))

In [34]:
# Find maximum
torch.max(x), x.max()

(tensor(9), tensor(9))

In [35]:
# Find mean
# torch.mean(x), x.mean() # can only work on float
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(4.5000), tensor(4.5000))

In [36]:
# Summation
torch.sum(x), x.sum()

(tensor(45), tensor(45))

In [37]:
# Retrieve min, max value position / index
torch.argmin(x), torch.argmax(x)

(tensor(0), tensor(9))

In [38]:
# Matrix multiplication rules
# 1. Inner diemnsions must match
# 2. Outer dimentions decides the resulting matrix shape
tensor_shape_1 = torch.rand(3,4)
tensor_shape_2 = torch.rand(4,5)
# torch.matmul is same as torch.mm
torch.mm(tensor_shape_1, tensor_shape_2)

tensor([[1.8516, 0.6998, 0.4503, 1.0754, 1.1379],
        [1.3028, 0.5947, 0.4039, 0.5554, 0.6449],
        [1.9748, 0.6348, 0.5021, 0.9332, 1.0573]])

### **Matrix reshaping or mutation**


1. Transpose
2. Reshaping
3. stacking
4. squeezing
5. unsqueezing
6. Permuting


In [39]:
# tensor initial form
print (tensor_shape_1, tensor_shape_1.shape)
# tensor transpose
print (tensor_shape_1.T, tensor_shape_1.T.shape)

tensor([[0.9114, 0.1674, 0.6852, 0.6584],
        [0.4690, 0.4377, 0.6817, 0.2471],
        [0.5993, 0.5280, 0.4856, 0.7948]]) torch.Size([3, 4])
tensor([[0.9114, 0.4690, 0.5993],
        [0.1674, 0.4377, 0.5280],
        [0.6852, 0.6817, 0.4856],
        [0.6584, 0.2471, 0.7948]]) torch.Size([4, 3])


In [40]:
# Reshape input (if compatible with torch size)
# tensor items stays same
tensor_reshape_1 = tensor_shape_1.reshape(6,2)
tensor_shape_1, tensor_reshape_1, tensor_reshape_1.shape

(tensor([[0.9114, 0.1674, 0.6852, 0.6584],
         [0.4690, 0.4377, 0.6817, 0.2471],
         [0.5993, 0.5280, 0.4856, 0.7948]]),
 tensor([[0.9114, 0.1674],
         [0.6852, 0.6584],
         [0.4690, 0.4377],
         [0.6817, 0.2471],
         [0.5993, 0.5280],
         [0.4856, 0.7948]]),
 torch.Size([6, 2]))

In [41]:
# View of the original tensor in a different / same shape 
# tensor items stays same
# but shares the same memmory
x = tensor_shape_1.view(2,6)
x, x.shape

(tensor([[0.9114, 0.1674, 0.6852, 0.6584, 0.4690, 0.4377],
         [0.6817, 0.2471, 0.5993, 0.5280, 0.4856, 0.7948]]),
 torch.Size([2, 6]))

In [42]:
# Stacking
# Concatenates a sequence of tensors along a new dimension (dim)
# stacked tensors must be of same size
x_stacked = torch.stack([x,x,x,x])
x_stacked, x_stacked.shape

(tensor([[[0.9114, 0.1674, 0.6852, 0.6584, 0.4690, 0.4377],
          [0.6817, 0.2471, 0.5993, 0.5280, 0.4856, 0.7948]],
 
         [[0.9114, 0.1674, 0.6852, 0.6584, 0.4690, 0.4377],
          [0.6817, 0.2471, 0.5993, 0.5280, 0.4856, 0.7948]],
 
         [[0.9114, 0.1674, 0.6852, 0.6584, 0.4690, 0.4377],
          [0.6817, 0.2471, 0.5993, 0.5280, 0.4856, 0.7948]],
 
         [[0.9114, 0.1674, 0.6852, 0.6584, 0.4690, 0.4377],
          [0.6817, 0.2471, 0.5993, 0.5280, 0.4856, 0.7948]]]),
 torch.Size([4, 2, 6]))

In [43]:
# Stacking and change dimensions
x_stacked = torch.stack([x,x,x,x], dim=-1)
x_stacked, x_stacked.shape

(tensor([[[0.9114, 0.9114, 0.9114, 0.9114],
          [0.1674, 0.1674, 0.1674, 0.1674],
          [0.6852, 0.6852, 0.6852, 0.6852],
          [0.6584, 0.6584, 0.6584, 0.6584],
          [0.4690, 0.4690, 0.4690, 0.4690],
          [0.4377, 0.4377, 0.4377, 0.4377]],
 
         [[0.6817, 0.6817, 0.6817, 0.6817],
          [0.2471, 0.2471, 0.2471, 0.2471],
          [0.5993, 0.5993, 0.5993, 0.5993],
          [0.5280, 0.5280, 0.5280, 0.5280],
          [0.4856, 0.4856, 0.4856, 0.4856],
          [0.7948, 0.7948, 0.7948, 0.7948]]]),
 torch.Size([2, 6, 4]))

In [44]:
# Squeeze input to remove all the dimenions with value 1.
x_squeeze = torch.squeeze(x_stacked)
x_squeeze, x_squeeze.shape

(tensor([[[0.9114, 0.9114, 0.9114, 0.9114],
          [0.1674, 0.1674, 0.1674, 0.1674],
          [0.6852, 0.6852, 0.6852, 0.6852],
          [0.6584, 0.6584, 0.6584, 0.6584],
          [0.4690, 0.4690, 0.4690, 0.4690],
          [0.4377, 0.4377, 0.4377, 0.4377]],
 
         [[0.6817, 0.6817, 0.6817, 0.6817],
          [0.2471, 0.2471, 0.2471, 0.2471],
          [0.5993, 0.5993, 0.5993, 0.5993],
          [0.5280, 0.5280, 0.5280, 0.5280],
          [0.4856, 0.4856, 0.4856, 0.4856],
          [0.7948, 0.7948, 0.7948, 0.7948]]]),
 torch.Size([2, 6, 4]))

In [45]:
# Initializing tensor with extra 1-Dimesions for code validation
x = torch.arange(1.,10)
x_reshape = x.reshape(1,1,9)
print (f"Added 1-Dims: {x_reshape} \n x_reshape.shape: {x_reshape.shape}\n")

#squeeze
x_squeeze = torch.squeeze(x_reshape)
print (f"Sqeezed tensor: {x_squeeze} \n x_squeeze.shape {x_squeeze.shape}")


Added 1-Dims: tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]]) 
 x_reshape.shape: torch.Size([1, 1, 9])

Sqeezed tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) 
 x_squeeze.shape torch.Size([9])


In [46]:
#unsqueeze
x_unsqueeze = x_squeeze.unsqueeze(dim=0)
x_unsqueeze, x_unsqueeze.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [47]:
#Permute 
#returns a view of the original tensor input with its dimensions permuted.
x = torch.randn(2, 3, 5)
x_permute = torch.permute(x, (2,0,1))
x, x.size(), x_permute, x_permute.size()

(tensor([[[ 2.4647,  1.0705, -0.9291,  0.2879,  1.0401],
          [-0.6524,  0.0546,  0.4875, -1.3746, -1.3367],
          [-0.1441,  1.8041, -1.0083, -1.5532, -0.4028]],
 
         [[-1.6559,  1.5262, -1.5814,  0.6306, -0.0597],
          [-0.0672,  0.2666, -0.2086,  0.2133, -1.4403],
          [-0.7273, -1.1414, -0.7290,  0.7874, -1.0675]]]),
 torch.Size([2, 3, 5]),
 tensor([[[ 2.4647, -0.6524, -0.1441],
          [-1.6559, -0.0672, -0.7273]],
 
         [[ 1.0705,  0.0546,  1.8041],
          [ 1.5262,  0.2666, -1.1414]],
 
         [[-0.9291,  0.4875, -1.0083],
          [-1.5814, -0.2086, -0.7290]],
 
         [[ 0.2879, -1.3746, -1.5532],
          [ 0.6306,  0.2133,  0.7874]],
 
         [[ 1.0401, -1.3367, -0.4028],
          [-0.0597, -1.4403, -1.0675]]]),
 torch.Size([5, 2, 3]))

##**Indexing (selecting data from tensor)**
Similar to Python lists or NumPy arrays

In [48]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [49]:
#Index and dimension concept
x[0], x[0][0], x[0,0] # x[0][0] same as x[0,0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor([1, 2, 3]))

In [50]:
# first (1-D) dimension is 0th dim
# try to select any item
x[0][0][0], x[0,0,0], x[0,1,1], x[0,2,2]

(tensor(1), tensor(1), tensor(5), tensor(9))

In [51]:
#use ":" to specify "all values in this dimension"
x[:,:,:], x[:], x[:,:]

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

In [52]:
# select row, column or an element using ":"
x[:,:,0], x[:,1,:], x[:,1,2], x[:,:,2]

(tensor([[1, 4, 7]]), tensor([[4, 5, 6]]), tensor([6]), tensor([[3, 6, 9]]))

## **PyTorch tensors & NumPy**
1. NumPy array -> PyTorch tensor: `torch.from_numpy(ndarray)`
2. PyTorch tensor -> NumPy array: `torch.Tensor.numpy()`

In [55]:
# NumPy array Integer 
array = np.arange(1,10)
array, array.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int64'))

In [61]:
# NumPy array float
# default float datatype is float64
array = np.arange(1.,10.)
array, array.dtype

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]), dtype('float64'))

In [60]:
# Numpy Convert datatype
np.float32(array)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [63]:
# NumPy array to PyTorch tensor
# default datatype of numpy float64 propagetes in tensor 
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [66]:
# go back to float32 datatype
tensor.type(torch.float32), tensor.type(torch.float32).dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [67]:
# tensor stays same if arrary changed and vice versa
array = array + 1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [71]:
# PyTorch tensor to NumPy array
tensor = torch.ones(5) # default dtype=float32
tensor_to_numpy = tensor.numpy() #torch default dtype assigned to numpy
tensor, tensor.dtype, tensor_to_numpy

(tensor([1., 1., 1., 1., 1.]),
 torch.float32,
 array([1., 1., 1., 1., 1.], dtype=float32))

## **Reproducibility (trying to take the random out of random)**
To perform repeatable experiments.
I can create an algorithm capable of achieving X performance. Another person tries it out to verify and want to achieve same X performance. Here **reproducibility** comes in.

In [74]:
#create two random tensors
tensor_random_A = torch.rand(3,4)
tensor_random_B = torch.rand(3,4)
print(tensor_random_A)
print(tensor_random_B)
print(f"If tensors are equal: \n {tensor_random_A == tensor_random_B}")

tensor([[0.1737, 0.1824, 0.4700, 0.4305],
        [0.8259, 0.7654, 0.3560, 0.9769],
        [0.6967, 0.0978, 0.3476, 0.0354]])
tensor([[0.1147, 0.0996, 0.6638, 0.4815],
        [0.0648, 0.7304, 0.0379, 0.3559],
        [0.1187, 0.8653, 0.2511, 0.4076]])
If tensors are equal: 
 tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
