<a href="https://colab.research.google.com/github/tapodeb/data_science/blob/main/PyTorch_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch Fundamentals**

## **Introduction to Tensors**
1. Scalar
2. Vector
3. Matrix

Initialization using random, arange, zeros, ones, eyes

Basic Operations

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print (torch.__version__)

2.0.1+cu118


In [6]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
#check the dimensions of a tensor using the ndim attribute
scalar.ndim

0

In [8]:
#retrieve the number from the tensor OR turn it from torch.Tensor to a Python integer
scalar.item()

7

In [9]:
#vector
vector = torch.tensor([2,3])
vector

tensor([2, 3])

In [10]:
# Check the number of dimensions of vector
vector.ndim

1

In [11]:
#shape defines how the tensor elements are arranged
vector.shape

torch.Size([2])

In [12]:
#Matrix
MATRIX = torch.tensor([[1,2,3],[4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 3])

In [15]:
#index
MATRIX[0]

tensor([1, 2, 3])

In [16]:
#check the tensor dimensions by changing the number of [] brackets
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [6,7,9]]])
print (TENSOR)
TENSOR.shape

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 9]]])


torch.Size([1, 3, 3])

In [17]:
#random tensor
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4643, 0.0321, 0.9032, 0.1855],
        [0.7591, 0.7735, 0.7520, 0.9712],
        [0.2291, 0.1037, 0.2223, 0.2082]])

In [18]:
#tensor of zeros
zeros = torch.zeros(2,5)
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [19]:
#tensor of ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
#identity matrix
I_s = torch.eye(3,5)
I_s

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [21]:
#reset values
random_tensor = torch.rand(3, 4)
print (random_tensor)
zeros = torch.zeros(1)
print(zeros)
random_tensor*zeros

tensor([[0.4956, 0.3688, 0.1195, 0.0516],
        [0.4798, 0.8699, 0.9699, 0.1989],
        [0.2908, 0.4538, 0.9876, 0.7329]])
tensor([0.])


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
#Range
torch.range(1,10)

<ipython-input-22-3785c09540d6>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
#As torch.range might get removed in future - check previous warning, use this
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#craeting tensor of same shape
one_to_ten = torch.arange(start=1, end =11, step=1)
print(one_to_ten)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## **Data Type**
https://pytorch.org/docs/stable/tensors.html

In [25]:
#tensor datatype and attributes
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device


(torch.Size([3]), torch.float32, device(type='cpu'))

In [26]:
# torch.half: half precion than default float32
float_16_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float16) #dtype=torch.half also work
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [27]:
# torch.double: double precion than default float32
float_64_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float64) #dtype=torch.double also work
float_64_tensor, float_64_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float64), torch.float64)

In [28]:
#results to the higher precision data type in a calculation 
tensor_mult_1 = float_32_tensor*float_16_tensor
tensor_mult_2 = float_32_tensor*float_64_tensor
tensor_mult_1.dtype, tensor_mult_2.dtype

(torch.float32, torch.float64)

In [29]:
tensor_add_1 = float_32_tensor+float_16_tensor
tensor_add_2 = float_32_tensor+float_64_tensor
tensor_add_1.dtype, tensor_add_2.dtype

(torch.float32, torch.float64)

## **Math Operations**
Site: https://www.mathsisfun.com/algebra/matrix-multiplying.html

Calculator: https://www.mathsisfun.com/algebra/matrix-calculator.html

Another visual calculator: http://matrixmultiplication.xyz/

In [30]:
# basic math operation
tensor = torch.tensor([1,2,3])
tensor * 10, tensor + 10, tensor - 10, tensor / 10, tensor / 0

(tensor([10, 20, 30]),
 tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([0.1000, 0.2000, 0.3000]),
 tensor([inf, inf, inf]))

In [31]:
# matrix multiplication and dot product
print(f"element-wise multiplication: {tensor} * {tensor} = {tensor * tensor}")
print(f"dot product: torch.matmul(tensor, tensor) = {torch.matmul(tensor, tensor)}")

element-wise multiplication: tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])
dot product: torch.matmul(tensor, tensor) = 14


In [32]:
# In math matrix dot operation is represted as (1,2,3).(1,2,3)
# Above will be solved as 
1*1 + 2*2 + 3*3 

14

In [33]:
# above math can be performed in a python for loop, 
# it gets more complex as the matrix shape increases
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]+tensor[i]
print(value)

tensor(12)
CPU times: user 381 µs, sys: 0 ns, total: 381 µs
Wall time: 389 µs


In [34]:
#using torch is much faster, simple code
%%time
torch.matmul(tensor, tensor)

CPU times: user 41 µs, sys: 0 ns, total: 41 µs
Wall time: 44.1 µs


tensor(14)

In [35]:
#Tensor aggregation: min, max, mean, sum
x = torch.arange(0,10,1)
x, x.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

In [36]:
# Find minimum
torch.min(x), x.min()

(tensor(0), tensor(0))

In [37]:
# Find maximum
torch.max(x), x.max()

(tensor(9), tensor(9))

In [38]:
# Find mean
# torch.mean(x), x.mean() # can only work on float
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(4.5000), tensor(4.5000))

In [39]:
# Summation
torch.sum(x), x.sum()

(tensor(45), tensor(45))

In [40]:
# Retrieve min, max value position / index
torch.argmin(x), torch.argmax(x)

(tensor(0), tensor(9))

In [41]:
# Matrix multiplication rules
# 1. Inner diemnsions must match
# 2. Outer dimentions decides the resulting matrix shape
tensor_shape_1 = torch.rand(3,4)
tensor_shape_2 = torch.rand(4,5)
# torch.matmul is same as torch.mm
torch.mm(tensor_shape_1, tensor_shape_2)

tensor([[1.7045, 1.4479, 1.0388, 1.1209, 1.6421],
        [1.2898, 1.3104, 0.8120, 0.5783, 1.1654],
        [1.5198, 1.2316, 1.3390, 1.4564, 1.7628]])

## **Matrix reshaping or mutation**


1. Transpose
2. Reshaping
3. stacking
4. squeezing
5. unsqueezing
6. Permuting


In [42]:
# tensor initial form
print (tensor_shape_1, tensor_shape_1.shape)
# tensor transpose
print (tensor_shape_1.T, tensor_shape_1.T.shape)

tensor([[0.1728, 0.8116, 0.8333, 0.6456],
        [0.1269, 0.7847, 0.7352, 0.0185],
        [0.7520, 0.9248, 0.4240, 0.4598]]) torch.Size([3, 4])
tensor([[0.1728, 0.1269, 0.7520],
        [0.8116, 0.7847, 0.9248],
        [0.8333, 0.7352, 0.4240],
        [0.6456, 0.0185, 0.4598]]) torch.Size([4, 3])


In [43]:
# Reshape input (if compatible with torch size)
# tensor items stays same
tensor_reshape_1 = tensor_shape_1.reshape(6,2)
tensor_shape_1, tensor_reshape_1, tensor_reshape_1.shape

(tensor([[0.1728, 0.8116, 0.8333, 0.6456],
         [0.1269, 0.7847, 0.7352, 0.0185],
         [0.7520, 0.9248, 0.4240, 0.4598]]),
 tensor([[0.1728, 0.8116],
         [0.8333, 0.6456],
         [0.1269, 0.7847],
         [0.7352, 0.0185],
         [0.7520, 0.9248],
         [0.4240, 0.4598]]),
 torch.Size([6, 2]))

In [44]:
# View of the original tensor in a different / same shape 
# tensor items stays same
# but shares the same memmory
x = tensor_shape_1.view(2,6)
x, x.shape

(tensor([[0.1728, 0.8116, 0.8333, 0.6456, 0.1269, 0.7847],
         [0.7352, 0.0185, 0.7520, 0.9248, 0.4240, 0.4598]]),
 torch.Size([2, 6]))

In [45]:
# Stacking
# Concatenates a sequence of tensors along a new dimension (dim)
# stacked tensors must be of same size
x_stacked = torch.stack([x,x,x,x])
x_stacked, x_stacked.shape

(tensor([[[0.1728, 0.8116, 0.8333, 0.6456, 0.1269, 0.7847],
          [0.7352, 0.0185, 0.7520, 0.9248, 0.4240, 0.4598]],
 
         [[0.1728, 0.8116, 0.8333, 0.6456, 0.1269, 0.7847],
          [0.7352, 0.0185, 0.7520, 0.9248, 0.4240, 0.4598]],
 
         [[0.1728, 0.8116, 0.8333, 0.6456, 0.1269, 0.7847],
          [0.7352, 0.0185, 0.7520, 0.9248, 0.4240, 0.4598]],
 
         [[0.1728, 0.8116, 0.8333, 0.6456, 0.1269, 0.7847],
          [0.7352, 0.0185, 0.7520, 0.9248, 0.4240, 0.4598]]]),
 torch.Size([4, 2, 6]))

In [46]:
# Stacking and change dimensions
x_stacked = torch.stack([x,x,x,x], dim=-1)
x_stacked, x_stacked.shape

(tensor([[[0.1728, 0.1728, 0.1728, 0.1728],
          [0.8116, 0.8116, 0.8116, 0.8116],
          [0.8333, 0.8333, 0.8333, 0.8333],
          [0.6456, 0.6456, 0.6456, 0.6456],
          [0.1269, 0.1269, 0.1269, 0.1269],
          [0.7847, 0.7847, 0.7847, 0.7847]],
 
         [[0.7352, 0.7352, 0.7352, 0.7352],
          [0.0185, 0.0185, 0.0185, 0.0185],
          [0.7520, 0.7520, 0.7520, 0.7520],
          [0.9248, 0.9248, 0.9248, 0.9248],
          [0.4240, 0.4240, 0.4240, 0.4240],
          [0.4598, 0.4598, 0.4598, 0.4598]]]),
 torch.Size([2, 6, 4]))

In [47]:
# Squeeze input to remove all the dimenions with value 1.
x_squeeze = torch.squeeze(x_stacked)
x_squeeze, x_squeeze.shape

(tensor([[[0.1728, 0.1728, 0.1728, 0.1728],
          [0.8116, 0.8116, 0.8116, 0.8116],
          [0.8333, 0.8333, 0.8333, 0.8333],
          [0.6456, 0.6456, 0.6456, 0.6456],
          [0.1269, 0.1269, 0.1269, 0.1269],
          [0.7847, 0.7847, 0.7847, 0.7847]],
 
         [[0.7352, 0.7352, 0.7352, 0.7352],
          [0.0185, 0.0185, 0.0185, 0.0185],
          [0.7520, 0.7520, 0.7520, 0.7520],
          [0.9248, 0.9248, 0.9248, 0.9248],
          [0.4240, 0.4240, 0.4240, 0.4240],
          [0.4598, 0.4598, 0.4598, 0.4598]]]),
 torch.Size([2, 6, 4]))

In [48]:
# Initializing tensor with extra 1-Dimesions for code validation
x = torch.arange(1.,10)
x_reshape = x.reshape(1,1,9)
print (f"Added 1-Dims: {x_reshape} \n x_reshape.shape: {x_reshape.shape}\n")

#squeeze
x_squeeze = torch.squeeze(x_reshape)
print (f"Sqeezed tensor: {x_squeeze} \n x_squeeze.shape {x_squeeze.shape}")


Added 1-Dims: tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]]) 
 x_reshape.shape: torch.Size([1, 1, 9])

Sqeezed tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) 
 x_squeeze.shape torch.Size([9])


In [49]:
#unsqueeze
x_unsqueeze = x_squeeze.unsqueeze(dim=0)
x_unsqueeze, x_unsqueeze.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [50]:
#Permute 
#returns a view of the original tensor input with its dimensions permuted.
x = torch.randn(2, 3, 5)
x_permute = torch.permute(x, (2,0,1))
x, x.size(), x_permute, x_permute.size()

(tensor([[[-0.3813,  0.2525, -0.0530,  0.2057, -1.5589],
          [ 0.1957,  0.1011, -0.7643, -2.2190, -0.0353],
          [ 0.9604,  0.3057, -1.5832, -1.1394,  0.6436]],
 
         [[-0.8754, -0.3049, -0.2622,  1.1766, -0.0322],
          [-1.2573,  1.1138,  2.6386, -0.0764, -0.9682],
          [-0.4413,  1.8433, -1.9048,  1.9236,  0.5222]]]),
 torch.Size([2, 3, 5]),
 tensor([[[-0.3813,  0.1957,  0.9604],
          [-0.8754, -1.2573, -0.4413]],
 
         [[ 0.2525,  0.1011,  0.3057],
          [-0.3049,  1.1138,  1.8433]],
 
         [[-0.0530, -0.7643, -1.5832],
          [-0.2622,  2.6386, -1.9048]],
 
         [[ 0.2057, -2.2190, -1.1394],
          [ 1.1766, -0.0764,  1.9236]],
 
         [[-1.5589, -0.0353,  0.6436],
          [-0.0322, -0.9682,  0.5222]]]),
 torch.Size([5, 2, 3]))

##**Indexing (selecting data from tensor)**
Similar to Python lists or NumPy arrays

In [51]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [52]:
#Index and dimension concept
x[0], x[0][0], x[0,0] # x[0][0] same as x[0,0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor([1, 2, 3]))

In [53]:
# first (1-D) dimension is 0th dim
# try to select any item
x[0][0][0], x[0,0,0], x[0,1,1], x[0,2,2]

(tensor(1), tensor(1), tensor(5), tensor(9))

In [54]:
#use ":" to specify "all values in this dimension"
x[:,:,:], x[:], x[:,:]

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

In [55]:
# select row, column or an element using ":"
x[:,:,0], x[:,1,:], x[:,1,2], x[:,:,2]

(tensor([[1, 4, 7]]), tensor([[4, 5, 6]]), tensor([6]), tensor([[3, 6, 9]]))

## **PyTorch tensors & NumPy**
1. NumPy array -> PyTorch tensor: `torch.from_numpy(ndarray)`
2. PyTorch tensor -> NumPy array: `torch.Tensor.numpy()`

In [56]:
# NumPy array Integer 
array = np.arange(1,10)
array, array.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int64'))

In [57]:
# NumPy array float
# default float datatype is float64
array = np.arange(1.,10.)
array, array.dtype

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]), dtype('float64'))

In [58]:
# Numpy Convert datatype
np.float32(array)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [59]:
# NumPy array to PyTorch tensor
# default datatype of numpy float64 propagetes in tensor 
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [60]:
# go back to float32 datatype
tensor.type(torch.float32), tensor.type(torch.float32).dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [61]:
# tensor stays same if arrary changed and vice versa
array = array + 1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [62]:
# PyTorch tensor to NumPy array
tensor = torch.ones(5) # default dtype=float32
tensor_to_numpy = tensor.numpy() #torch default dtype assigned to numpy
tensor, tensor.dtype, tensor_to_numpy

(tensor([1., 1., 1., 1., 1.]),
 torch.float32,
 array([1., 1., 1., 1., 1.], dtype=float32))

## **Reproducibility (trying to take the random out of random)**
To perform repeatable experiments.
I can create an algorithm capable of achieving X performance. Another person tries it out to verify and want to achieve same X performance. Here **reproducibility** comes in.

Python random: https://www.geeksforgeeks.org/python-random-module/

RNG: https://en.wikipedia.org/wiki/Random_number_generation#Computational_methods

(pseudo-)random numbers work by starting with a number (the seed), multiplying it by a large number, adding an offset, then taking modulo of that sum. The resulting number is then used as the seed to generate the next "random" number. When you set the seed (every time), it does the same thing every time, giving you the same numbers.

numpy/PyTorch set the seed to a random number obtained from /dev/urandom or its Windows analog or, if neither of those is available, it will use the clock.

In [63]:
#create two random tensors
tensor_random_A = torch.rand(3,4)
tensor_random_B = torch.rand(3,4)
print(tensor_random_A)
print(tensor_random_B)
print(f"If tensors are equal: \n {tensor_random_A == tensor_random_B}")

tensor([[0.7046, 0.4925, 0.5680, 0.6293],
        [0.6343, 0.5358, 0.7776, 0.2539],
        [0.7163, 0.3560, 0.7059, 0.3078]])
tensor([[7.4187e-01, 4.7318e-01, 9.5787e-01, 9.2185e-04],
        [7.5016e-01, 2.8866e-01, 6.3147e-01, 5.7458e-02],
        [4.5432e-01, 6.3251e-01, 9.9476e-01, 3.0390e-01]])
If tensors are equal: 
 tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [64]:
#import torch
#import random
RANDOM_SEED = 44
torch.manual_seed(seed=RANDOM_SEED)
tensor_random_A = torch.rand(3,4)
torch.manual_seed(seed=RANDOM_SEED)
tensor_random_B = torch.rand(3,4)

print(tensor_random_A)
print(tensor_random_B)
print(f"If tensors are equal: \n {tensor_random_A == tensor_random_B}")

tensor([[0.7196, 0.7307, 0.8278, 0.1343],
        [0.6280, 0.7297, 0.2882, 0.2112],
        [0.9836, 0.8722, 0.9650, 0.7837]])
tensor([[0.7196, 0.7307, 0.8278, 0.1343],
        [0.6280, 0.7297, 0.2882, 0.2112],
        [0.9836, 0.8722, 0.9650, 0.7837]])
If tensors are equal: 
 tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [65]:
# In python random.seed() in PyTorch torch.manual_seed()
import random
 
random.seed(5)
print(random.random())

random.seed(5)
print(random.random())

0.6229016948897019
0.6229016948897019


In [67]:
#Numpy also has its own random method
import numpy as np

np.random.seed(5)
print(np.random.random())

np.random.seed(5)
print(np.random.random())

0.22199317108973948
0.22199317108973948


Reproducible results may/will vary across:
1. PyTorch releases, 
2. individual commits, 
3. different platforms,
4. devices (CPU and GPU).

Limit randomness
1. Avoid multiple executions of your application.
2. Avoid multiple calls to those operations.

## **Device**

Nvidia GPU with CUDA driver installed is recommended
https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/

Device-agnostic code:  
https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code

In [ ]:
!nvidia-smi

Mon Jun 12 02:47:10 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# Check for GPU and count of GPU(s)
torch.cuda.is_available(), torch.cuda.device_count()

(True, 1)

In [71]:
# Simple Device-agnostic code
# better code is in documentation
device = "cuda" if torch.cuda.is_available() else "CPU"
device

'cuda'

In [75]:
# create a tensor (default on CPU)
tensor = torch.tensor([1, 3, 4, 6])
tensor, tensor.device

(tensor([1, 3, 4, 6]), device(type='cpu'))

In [79]:
# move tensor to GPU if available
tensor_to_gpu = tensor.to(device)
tensor_to_gpu

tensor([1, 3, 4, 6], device='cuda:0')

In [85]:
# move tensor back to cpu
tensor_back_to_cpu = tensor_to_gpu.cpu()
tensor_back_to_cpu, tensor_back_to_cpu.device

(tensor([1, 3, 4, 6]), device(type='cpu'))

In [91]:
# tensors physically moved to other devices. Not copied.
tensor, tensor.device, tensor_to_gpu, tensor_back_to_cpu.device, tensor_back_to_cpu, tensor_back_to_cpu.device

(tensor([1, 3, 4, 6]),
 device(type='cpu'),
 tensor([1, 3, 4, 6], device='cuda:0'),
 device(type='cpu'),
 tensor([1, 3, 4, 6]),
 device(type='cpu'))

In [88]:
# Numpy does not work on GPU
#tensor_to_gpu.numpy()

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-86-14c649e28ccc> in <cell line: 2>()
      1 # Numpy does not work on GPU
----> 2 tensor_to_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.`

In [89]:
# Numpy only works on CPU
tensor_back_to_cpu.numpy()

array([1, 3, 4, 6])

# **PyTorch Workflows**
Machine Learning:
1. Get data into a numerical representation.
2. Build a model to learn the patterns in that numerical representation.

In [ ]:
import torch
from torch import nn # contains PyTorch building blocks for Neural networks
import matplotlib.pyplot as plt
